sudo: false
language: node_js
node_js:
 - 0.12
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- cd TM_4_0_Design
- npm install
- npm test
- npm start &
- cd ..
- cd TM_4_0_GraphDB
- mkdir ./.tmCache
- git clone https://tm-build:$git_pwd@github.com/TMContent/Lib_UNO-json.git ./.tmCache/Lib_UNO-json
- npm install
- npm test
- npm run dev &
- cd ..
notifications:
  slack:
    secure: d9spkOFp62ic85Oovs/vuHOAAMCNXdmkvMSFeJGqpD70NxixNm3EJNAg9u34dq1OvyPkItbjHZZU6B/CEUwSTPcIsyJOsSO1g95hYT95LXOtvVdqXnLQL92ADZ/zT8bI5yYWu/E+JIeEyr8sbEMXBU5KVkxHfWSHo7xugNdhL/A=
