sudo: false
language: node_js
node_js:
- 0.12
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- cd TM_4_0_Design
- mkdir ./.tmCache
- git clone https://github.com/TMContent/Lib_Docs-json ./.tmCache/Lib_Docs-json
- npm install
- npm test
- npm start &
- cd ..
- cd TM_4_0_GraphDB
- mkdir ./.tmCache
- git clone https://$git_pwd@github.com/TMContent/Lib_UNO-json.git ./.tmCache/Lib_UNO-json
- npm install
- npm test
- npm run dev &
- cd ..
notifications:
  slack:
    secure: d9spkOFp62ic85Oovs/vuHOAAMCNXdmkvMSFeJGqpD70NxixNm3EJNAg9u34dq1OvyPkItbjHZZU6B/CEUwSTPcIsyJOsSO1g95hYT95LXOtvVdqXnLQL92ADZ/zT8bI5yYWu/E+JIeEyr8sbEMXBU5KVkxHfWSHo7xugNdhL/A=
env:
  global:
  - secure: lOPm0Nt9Hen7gDDaI+Q+NmQelSaxsXJirtbSCT63RhE+o8rD3Dso9N3F4b37mxXH14hiHygOda2JRz5IYZtiYgUkD3QlTPebydJI/qxlmL1/NtxCMaYI/ZKAW8C3fMeqpOpvVtGTQb8Npn+6VFSbSoukOAI2w/cK25hnf6abTleXB+Lidnza7WReXg6UkZOtW1+OFWgqWcP7OV7oZYeccjQNGxCAIE1m0fIHdcmd2ParHmYVWmbYwUq4/ylO/Dfxvee7yQgLAYt5P8ImU6w8QO0yOaeQPFsZWx+OqSIVIwu37ZCuEbLvICl19H/RBev9qxy9pyvsfsRBTksAO1ivR8Jn4oCGbqfxaSwfl7WCl9bE7ph45xZIN/waWsKmSa4Y5bD8jXhwqCqISd4PEM1oPc+4BwJZH7OW3CIhWxp//hsEbo1+bX0LXKwJQPp8LIDeLRGuj/Pn+tI+PqWLn35/XlS3omPrluMZ+r9RhVKPBDDTXDL4qU91wFN13zMFTSxB3sTZmQl5HWxSO+vsr/thBQELgAwZj6pxRZZqf3TEuUwbiD1VsQrX97kUfAgAqrqNZ1KPPjMZR5jcheSAI9YGjW2HhDsZvfK/0u2vfcX3VxTq70V+obIzCzszly0BZVU11mvvmA8XnyUHZPIO7U6tOcoFibgsJuh5sBbMyuoVCmw=
